name: kwin
on:
  push:
    branches: [main, pr-22]
    paths: ['kwin/**', 'oci/**', '.github/workflows/kwin.yml', '.github/workflows/_package-image.yml', 'toolchain.env']
  workflow_dispatch:
permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  build:
    uses: ./.github/workflows/_package-image.yml
    secrets: inherit
    with:
      package: kwin
